// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtY8Fz0fVTm3MkGCtIass5HNDvL05enAA',
    appId: '1:95208587543:web:6e21f8bcb0734853f6b752',
    messagingSenderId: '95208587543',
    projectId: 'ktpm-2023',
    authDomain: 'ktpm-2023.firebaseapp.com',
    databaseURL: 'https://ktpm-2023-default-rtdb.firebaseio.com',
    storageBucket: 'ktpm-2023.appspot.com',
    measurementId: 'G-1HR2QKZQDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnOU8NyO5unBbg6xkO2zj6Hlv9rPKNcdM',
    appId: '1:95208587543:android:311cea9979ecf1ccf6b752',
    messagingSenderId: '95208587543',
    projectId: 'ktpm-2023',
    databaseURL: 'https://ktpm-2023-default-rtdb.firebaseio.com',
    storageBucket: 'ktpm-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG8juaFlK5QPE-BeNjgeW2gVap-GFOY3E',
    appId: '1:95208587543:ios:29ab96371b641c29f6b752',
    messagingSenderId: '95208587543',
    projectId: 'ktpm-2023',
    databaseURL: 'https://ktpm-2023-default-rtdb.firebaseio.com',
    storageBucket: 'ktpm-2023.appspot.com',
    iosClientId: '95208587543-teh20vcjbeoad94c1ll1plrp2ae2hc5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.riderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG8juaFlK5QPE-BeNjgeW2gVap-GFOY3E',
    appId: '1:95208587543:ios:6bec875a4cde8897f6b752',
    messagingSenderId: '95208587543',
    projectId: 'ktpm-2023',
    databaseURL: 'https://ktpm-2023-default-rtdb.firebaseio.com',
    storageBucket: 'ktpm-2023.appspot.com',
    iosClientId: '95208587543-gpvdv9krt7u01hp4o10pmhj0ssbtospa.apps.googleusercontent.com',
    iosBundleId: 'com.example.riderApp.RunnerTests',
  );
}
